# SonarQube Project Configuration
sonar.projectKey=ACEest-Fitness-Gym
sonar.projectName=ACEest Fitness & Gym
sonar.projectVersion=1.0

# Source and Test directories
sonar.sources=app
sonar.tests=tests
sonar.python.version=3

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage report (relative path to artifacts)
sonar.python.coverage.reportPaths=coverage.xml
