apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aceest-fitness-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-backend
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest-fitness
      env: staging
  template:
    metadata:
      labels:
        app: aceest-fitness
        env: staging
    spec:
      containers:
      - name: backend
        image: ${DOCKER_IMAGE}
        ports:
        - containerPort: 5000
        env:
        - name: DB_DIR
          value: "/data"
        volumeMounts:
        - name: db-storage
          mountPath: /data
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: aceest-fitness-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-service
  namespace: staging
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30081
  selector:
    app: aceest-fitness
    env: staging
